-- Cambios BD 
--001.
ALTER TABLE tab_usuarios ADD COLUMN IF NOT EXISTS activo BOOLEAN DEFAULT TRUE;
--002.
ALTER TABLE tab_tipos ADD COLUMN IF NOT EXISTS activo BOOLEAN DEFAULT TRUE;
--003.
ALTER TABLE tab_marca ADD COLUMN IF NOT EXISTS activo BOOLEAN DEFAULT TRUE;
--004.
ALTER TABLE tab_modelo ADD COLUMN IF NOT EXISTS activo BOOLEAN DEFAULT TRUE;
--005.
ALTER TABLE tab_area ADD COLUMN IF NOT EXISTS activo BOOLEAN DEFAULT TRUE;
--006.
ALTER TABLE tab_activotec ADD COLUMN IF NOT EXISTS activo BOOLEAN DEFAULT TRUE;
--007.
ALTER TABLE tab_actualizaciones ALTER COLUMN fecha SET DEFAULT CURRENT_TIMESTAMP;
--008.
ALTER TABLE tab_novedades ADD COLUMN IF NOT EXISTS activo BOOLEAN DEFAULT TRUE;
ALTER TABLE tab_novedades ALTER COLUMN fecha_reporte SET DEFAULT CURRENT_TIMESTAMP;
-- Aseguramos un estado inicial por defecto
ALTER TABLE tab_novedades ALTER COLUMN estado_ticket SET DEFAULT 'ABIERTO';